apiVersion: v2
publisher: ibm
name: zopendebug
version: 1.0.1
type: VS Code extension
displayName: zopendebug
title: zopendebug
description: A test extension
icon: https://github.com/CoenraadS/BracketPair/raw/develop/images/icon.png
repository: https://github.com/nsharma1989/carbon-tutorial
category: Other
firstPublicationDate: '2019-10-19'
spec:
  extensions:
  - https://github.com/nsharma1989/my-plugin-registry/raw/master/ibm/zopendebug/1.0.1/zopendebug-1.0.0.vsix
