apiVersion: v2
publisher: ibm
name: zopendebug-profileui
version: 1.0.1
type: VS Code extension
displayName: zopendebug-profileui
title: zopendebug-profileui
description: A test extension
icon: https://github.com/CoenraadS/BracketPair/raw/develop/images/icon.png
repository: https://github.com/nsharma1989/carbon-tutorial
category: Other
firstPublicationDate: '2019-10-19'
spec:
  extensions:
  - http://tlbgsa.ibm.com/projects/d/debug_ui_builds/RTC/PDT_DAAS_WEB_UI/vNext/I/20200917-2230/zopendebug-profileui.vsix
