apiVersion: v2
publisher: ibm
name: wazi-debug
version: 1.1.0
type: VS Code extension
displayName: IBM Z Open Debug
title: IBM Z Open Debug
description: This VS Code extension provides support for IBM Z debugging, based on the IBM Z Open Debug extensions.
icon: https://raw.githubusercontent.com/IBM/zopendebug-about/master/images/ibm-z-open-debug.svg
repository: https://github.com/IBM/zopendebug-about.git
category: Language
firstPublicationDate: "2020-10-30"
spec:
  extensions:
  - https://github.com/nsharma1989/my-plugin-registry/raw/master/ibm/zopendebug-profileui/1.0.1/zopendebug-profileui.vsix
  - https://github.com/nsharma1989/my-plugin-registry/raw/master/ibm/zopendebug/1.0.1/zopendebug-1.0.0.vsix
