apiVersion: v2
publisher: ibm
name: zopendebug-extensions
version: 1.0.1
type: VS Code extension
displayName: zopendebug-extensions
title: zopendebug-extensions
description: A test extension
repository: https://github.com/nsharma1989/carbon-tutorial
category: Other
firstPublicationDate: '2019-10-19'
spec:
  containers:
  - image: 'http://docker.io/ibmcom/wazi-code-codeready@sha256:00b36bdfba28596b01fcaf3ef29c81f8e7e8ff3c7809617907a34f9a94c5403b'
    name: ibm-wazi
    memoryLimit: "3000Mi"
    args:
      - sh
      - -c
      - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
    volumes:
    - mountPath: "/home/wazi/.zowe"
      name: wazi
    - mountPath: "/home/wazi/.m2"
      name: m2
  extensions:
  - https://github.com/nsharma1989/my-plugin-registry/raw/master/ibm/zopendebug-profileui/1.0.1/zopendebug-profileui-1.2.0.vsix
  - https://github.com/nsharma1989/my-plugin-registry/raw/master/ibm/zopendebug/1.0.1/zopendebug-1.0.0.vsix
